"use client";
import { useState } from 'react';
import Link from 'next/link';
import { IconArrowUpRight, IconBuilding, IconCalendar, IconCheck, IconPlus, IconInbox, IconSparkle } from '@/components/ui/icons';
import { buttonClasses } from '@/components/ui/button';
import { formatRupees } from '@/lib/properties/basics';
import { localToday, summarize, type Booking, type DashboardProperty } from '@/lib/dashboard/analytics';

const shortDate = (date: string) => new Date(date + 'T12:00:00Z').toLocaleDateString('en-GB', { day:'numeric', month:'short', timeZone:'UTC' });
function Change({ current, previous }: { current: number; previous: number }) {
  if (!previous) return <span className="metric-note">{current ? 'No prior-period baseline' : 'No activity in this period'}</span>;
  const change = Math.round((current - previous) / previous * 100);
  return <span className="metric-note"><b className={change >= 0 ? 'positive' : 'negative'}>{change > 0 ? '+' : ''}{change}%</b> vs previous period</span>;
}
export function DashboardHome({ bookings = [], properties = [], today = localToday(), organizationName = 'your workspace', escalatedCount = 0 }: {
  bookings?: Booking[]; properties?: DashboardProperty[]; today?: string; organizationName?: string; escalatedCount?: number;
}) {
  const [days, setDays] = useState(30);
  const [propertyId, setPropertyId] = useState('all');
  const [chartMode, setChartMode] = useState<'value'|'count'>('value');
  const [selectedBucket, setSelectedBucket] = useState<number | null>(null);
  const data = summarize(bookings, properties, today, days, propertyId);
  const pending = bookings.filter(b => b.status === 'requested' && (propertyId === 'all' || b.property_id === propertyId)).length;
  const arrivals = bookings.filter(b => ['approved','paid','staying'].includes(b.status) && (b.start_date === today || b.end_date === today) && (propertyId === 'all' || b.property_id === propertyId)).length;
  const propertyName = (id: string) => properties.find(p => p.id === id)?.name ?? 'Property';
  const peak = Math.max(...data.buckets.map(b => b[chartMode]), chartMode === "value" ? 100000 : 4);
  const activeBucket = selectedBucket === null ? null : data.buckets[selectedBucket];
  let cursor = 0;
  const stops = data.status.map(s => { const start=cursor; cursor += data.bookings ? s.count/data.bookings*100 : 0; return `${s.color} ${start}% ${cursor}%`; });
  return <div className="dashboard-overview">
    <div className="overview-heading"><div><p className="workspace-eyebrow">Your hosting, at a glance</p><h1>Overview</h1><p>Here&apos;s what&apos;s happening at {organizationName}.</p></div><Link href="/dashboard/properties/new" className={buttonClasses('primary')}><IconPlus className="size-4" />Add property</Link></div>
    <div className="overview-filters"><div className="period-switch" aria-label="Analytics period">{[7,30,90].map(n=><button type="button" key={n} aria-pressed={days===n} onClick={()=>{setDays(n);setSelectedBucket(null);}}>Last {n} days</button>)}</div><div className="filter-right"><span className="date-range"><IconCalendar className="size-4" />{shortDate(data.start)} - {shortDate(today)}</span><select aria-label="Filter analytics by property" value={propertyId} onChange={e=>{setPropertyId(e.target.value);setSelectedBucket(null);}}><option value="all">All properties</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div>
    <section className="metric-grid" aria-label="Key metrics">
      <article className="metric-card featured"><div className="metric-label">Confirmed booking value<IconArrowUpRight /></div><strong>{formatRupees(data.value)}</strong><Change current={data.value} previous={data.previousValue} /><span className="metric-foot">Confirmed bookings created in this period</span></article>
      <article className="metric-card"><div className="metric-label">Booking requests<IconCalendar /></div><strong>{data.bookings}<span>bookings</span></strong><Change current={data.bookings} previous={data.previousBookings} /><span className="metric-foot">All booking statuses included</span></article>
      <article className="metric-card"><div className="metric-label">Occupancy<IconBuilding /></div><strong>{data.occupancy}<span>%</span></strong><span className="metric-note">{data.occupiedNights} booked property nights</span><span className="metric-foot">Across {data.properties} current {data.properties===1?'property':'properties'}</span></article>
      <article className="metric-card"><div className="metric-label">Published properties<IconCheck /></div><strong>{data.published}<span>/ {data.properties}</span></strong><span className="metric-note">{data.properties-data.published} draft {data.properties-data.published===1?'property':'properties'}</span><Link href="/dashboard/properties" className="metric-foot metric-link">Manage properties <IconArrowUpRight /></Link></article>
    </section>
    <div className="analytics-grid">
      <section className="dash-panel booking-chart"><div className="panel-heading"><div><h2>Booking activity</h2><p>A clearer view of how your hosting is growing.</p></div><div className="chart-switch">{(['value','count'] as const).map(mode=><button type="button" key={mode} aria-pressed={chartMode===mode} onClick={()=>setChartMode(mode)}>{mode==='value'?'Value':'Bookings'}</button>)}</div></div><div className="chart-summary"><strong>{chartMode==='value'?formatRupees(data.value):data.bookings.toLocaleString()}</strong><span>{chartMode==='value'?'Booking value, not payments received':'Requests created in the selected period'}</span></div>
        <div className="chart-plot"><div className="chart-y-axis" aria-hidden="true">{[1,.75,.5,.25,0].map(n=><span key={n}>{chartMode==='value'?formatRupees(Math.round(peak*n)):Math.ceil(peak*n)}</span>)}</div><div className="chart-bars">{data.buckets.map((b,i)=><button type="button" key={b.date} className={`chart-column ${selectedBucket===i?'selected':''}`} onClick={()=>setSelectedBucket(i)} onFocus={()=>setSelectedBucket(i)} aria-label={`${shortDate(b.date)} to ${shortDate(b.end)}: ${b.count} bookings, ${formatRupees(b.value)} confirmed value`} aria-pressed={selectedBucket===i}><span className="chart-bar" style={{height:b[chartMode] ? `${b[chartMode]/peak*100}%` : '2px'}} /><span className="chart-date">{shortDate(b.date)}</span></button>)}</div>{data.bookings===0 && <div className="chart-empty"><IconCalendar /><strong>Your next booking starts the story.</strong><span>Activity will appear here as guests request stays.</span></div>}</div>
        <div className="chart-caption" aria-live="polite">{activeBucket ? `${shortDate(activeBucket.date)} - ${shortDate(activeBucket.end)} · ${activeBucket.count} requests · ${formatRupees(activeBucket.value)} confirmed value` : 'Select a bar to explore the period. Dates use Pakistan time.'}</div>
      </section>
      <section className="dash-panel status-panel"><div className="panel-heading"><div><h2>Booking breakdown</h2><p>Requests by current status</p></div></div><div className="status-ring" role="img" aria-label={`${data.bookings} bookings: ${data.status.map(s=>`${s.count} ${s.label.toLowerCase()}`).join(', ')}`} style={{background: data.bookings?`conic-gradient(${stops.join(',')})`:'#e9ede4'}}><div><strong>{data.bookings}</strong><span>Total requests</span></div></div><div className="status-legend">{data.status.map(s=><div key={s.label}><span className="legend-dot" style={{background:s.color}} /><span>{s.label}</span><strong>{s.count}</strong><small>{data.bookings?Math.round(s.count/data.bookings*100):0}%</small></div>)}</div><p className="panel-footnote">Confirmed includes approved, paid, staying and completed stays.</p></section>
    </div>
    <div className="operations-grid">
      <section className="dash-panel recent-panel"><div className="panel-heading"><div><h2>Recent bookings</h2><p>The latest requests across your properties.</p></div><span className="count-chip">{data.bookings} this period</span></div><div className="booking-table-wrap"><table className="booking-table"><thead><tr><th>Property / reference</th><th>Stay dates</th><th>Status</th><th>Booking value</th></tr></thead><tbody>{data.recent.map(b=><tr key={b.id}><td><Link href={`/dashboard/properties/${b.property_id}`}>{propertyName(b.property_id)}</Link><small>#{b.id.slice(0,8).toUpperCase()}</small></td><td>{shortDate(b.start_date)} - {shortDate(b.end_date)}<small>{Math.round((Date.parse(b.end_date)-Date.parse(b.start_date))/86400000)} nights</small></td><td><span className={`booking-status status-${b.status}`}>{b.status.replace('_',' ')}</span></td><td>{formatRupees(b.total_price_cents)}</td></tr>)}</tbody></table></div>{!data.recent.length&&<div className="panel-empty"><span><IconInbox /></span><h3>No bookings in this period</h3><p>Your booking requests will appear here, ready for a closer look.</p><Link href="/dashboard/properties">Manage your properties <IconArrowUpRight /></Link></div>}</section>
      <section className="dash-panel attention-panel"><div className="panel-heading"><div><h2>Needs your attention</h2><p>A little focus for the day ahead.</p></div></div><div className="attention-row"><span className="attention-icon"><IconCalendar /></span><div><strong>Waiting booking requests</strong><small>Across the selected properties</small></div><b>{pending}</b></div><div className="attention-row"><span className="attention-icon"><IconSparkle /></span><div><strong>Escalated chats</strong><small>Across your whole workspace</small></div><b>{escalatedCount}</b></div><div className="attention-row"><span className="attention-icon"><IconBuilding /></span><div><strong>Today&apos;s arrivals and departures</strong><small>{shortDate(today)}</small></div><b>{arrivals}</b></div>{pending+escalatedCount+arrivals===0&&<div className="all-clear"><IconCheck className="size-4" />Nothing needs you right now.</div>}<p className="panel-footnote">Unread messages: read tracking is not available yet.</p></section>
    </div>
    <div className="operations-grid bottom-grid"><section className="dash-panel"><div className="panel-heading"><div><h2>Property performance</h2><p>Confirmed booking value in this period</p></div><Link href="/dashboard/properties" className="panel-link">View properties <IconArrowUpRight /></Link></div>{data.performance.length ? <div className="performance-list">{data.performance.map(p=><Link href={`/dashboard/properties/${p.id}`} key={p.id}><span className="property-avatar"><IconBuilding /></span><div><strong>{p.name}</strong><small>{p.count} bookings · {p.published?'Published':'Draft'}</small></div><b>{formatRupees(p.value)}</b><IconArrowUpRight /></Link>)}</div>:<div className="compact-empty"><IconBuilding /><p>Add your first property to start tracking performance.</p><Link href="/dashboard/properties/new">Add property <IconPlus className="size-4" /></Link></div>}</section><section className="dash-panel"><div className="panel-heading"><div><h2>Upcoming stays</h2><p>Confirmed stays from today onward</p></div><IconCalendar className="size-5 text-muted" /></div>{data.upcoming.length?<div className="upcoming-list">{data.upcoming.map(b=><Link key={b.id} href={`/dashboard/properties/${b.property_id}`}><span className="stay-date"><b>{b.start_date.slice(8)}</b><small>{new Date(b.start_date+'T12:00:00Z').toLocaleDateString('en',{month:'short',timeZone:'UTC'})}</small></span><div><strong>{propertyName(b.property_id)}</strong><small>{shortDate(b.start_date)} - {shortDate(b.end_date)}</small></div><span className="booking-status">{b.status.replace('_',' ')}</span></Link>)}</div>:<div className="compact-empty"><IconCalendar /><p>No upcoming stays just yet.<br />Your next arrivals will appear here.</p></div>}</section></div>
  </div>;
}
